import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* ── 1. NUMERICAL PRIMITIVE SHADE LADDERS (50–950) ── */
        parchment: {
          50: "var(--parchment-50)",
          100: "var(--parchment-100)",
          200: "var(--parchment-200)",
          300: "var(--parchment-300)",
          400: "var(--parchment-400)",
          500: "var(--parchment-500)",
          600: "var(--parchment-600)",
          700: "var(--parchment-700)",
          800: "var(--parchment-800)",
          900: "var(--parchment-900)",
          950: "var(--parchment-950)",
        },
        forest: {
          50: "var(--forest-50)",
          100: "var(--forest-100)",
          200: "var(--forest-200)",
          300: "var(--forest-300)",
          400: "var(--forest-400)",
          500: "var(--forest-500)",
          600: "var(--forest-600)",
          700: "var(--forest-700)",
          800: "var(--forest-800)",
          900: "var(--forest-900)",
          950: "var(--forest-950)",
        },
        action: {
          50: "var(--action-50)",
          100: "var(--action-100)",
          200: "var(--action-200)",
          300: "var(--action-300)",
          400: "var(--action-400)",
          500: "var(--action-500)",
          600: "var(--action-600)",
          700: "var(--action-700)",
          800: "var(--action-800)",
          900: "var(--action-900)",
          950: "var(--action-950)",
        },
        neutral: {
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          900: "var(--neutral-900)",
          950: "var(--neutral-950)",
        },

        /* ── 2. FUNCTIONAL SEMANTIC TOKENS ─────────────────── */
        surface: {
          canvas: "var(--bg-canvas)",
          elevated: "var(--bg-surface-elevated)",
          recessed: "var(--bg-surface-recessed)",
          muted: "var(--bg-section-muted)",
          inverted: "var(--bg-section-inverted)",
          "inverted-card": "var(--bg-section-inverted-card)",
          overlay: "var(--surface-overlay)",
        },

        /* ── 3. APPLICATION & BACKWARD COMPATIBILITY TOKENS ── */
        canvas: {
          DEFAULT: "var(--canvas-base)",
          paper: "var(--surface-paper)",
          vellum: "var(--surface-tint-warm)",
          dark: "var(--surface-dark)",
          "dark-card": "var(--surface-dark-card)",
          surface: "var(--surface-paper)",
          recessed: "var(--surface-tint-warm)",
        },
        ink: {
          DEFAULT: "var(--ink-primary)",
          primary: "var(--ink-primary)",
          secondary: "var(--ink-secondary)",
          tertiary: "var(--ink-tertiary)",
          muted: "var(--text-ink-muted)",
          inverted: "var(--text-ink-inverted)",
          "inverted-muted": "var(--text-ink-inverted-muted)",
          hairline: "var(--border-hairline)",
          strong: "var(--border-strong)",
          border: "var(--border-strong)",
          "60": "var(--ink-secondary)",
          "40": "var(--ink-tertiary)",
          "20": "rgba(23, 20, 18, 0.20)",
          "10": "var(--border-hairline)",
          "05": "rgba(23, 20, 18, 0.05)",
        },
        rust: {
          DEFAULT: "var(--accent-rust)",
          hover: "var(--accent-rust-hover)",
          wash: "var(--accent-rust-wash)",
        },
        lapis: {
          DEFAULT: "var(--accent-lapis)",
          hover: "var(--accent-lapis-hover)",
          wash: "var(--accent-lapis-wash)",
        },
        moss: {
          DEFAULT: "var(--accent-moss)",
          hover: "var(--accent-moss-hover)",
          wash: "var(--accent-moss-wash)",
        },
        ochre: {
          DEFAULT: "var(--accent-ochre)",
          wash: "var(--accent-ochre-wash)",
        },
        celadon: "var(--accent-celadon)",
        olive: {
          DEFAULT: "var(--accent-moss)",
          lt: "#66784E",
        },
        warm: {
          bg: "var(--canvas-base)",
        },
        earth: "#8b6b4d",
        sky: "#234559",
      },
      fontFamily: {
        serif: ["var(--font-serif)", "Cormorant Garamond", "serif"],
        sans: ["var(--font-sans)", "DM Sans", "sans-serif"],
        mono: ["var(--font-mono)", "Fira Code", "monospace"],
      },
      fontSize: {
        "fs-200": "0.50rem",
        "fs-300": "0.8125rem",
        "fs-400": "1rem",
        "fs-500": "1.125rem",
        "fs-600": "1.3125rem",
        "fs-700": "1.625rem",
        "fs-800": "2.125rem",
        "fs-900": "3.25rem",
        display: "clamp(2.8rem, 6vw, 5.5rem)",
        "fluid-h1": "clamp(3.2rem, 8vw + 1rem, 7rem)",
        "fluid-h2": "clamp(2.4rem, 4vw + 0.5rem, 4.5rem)",
        "fluid-h3": "clamp(1.8rem, 4.5vw, 3rem)",
        "fluid-h4": "clamp(1.5rem, 3.5vw, 2.25rem)",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "8rem",
        "space-5xl": "10rem",
      },
      borderRadius: {
        sharp: "var(--radius-sharp)",
        card: "var(--radius-card)",
        dock: "var(--radius-dock)",
        "sm-custom": "8px",
        "md-custom": "12px",
        "lg-custom": "16px",
      },
      boxShadow: {
        plate: "var(--shadow-plate)",
        dock: "var(--shadow-dock)",
        "dark-plate": "var(--shadow-dark-card)",
        "soft-sm": "0 1px 3px rgba(23, 20, 18, 0.04)",
        "soft-md": "0 4px 16px rgba(23, 20, 18, 0.06)",
        "soft-lg": "0 12px 32px rgba(23, 20, 18, 0.08)",
      },
      transitionTimingFunction: {
        editorial: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
